version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/Qualidade-de-Software/frontend/dama"
    target-branch: "main"
    schedule:
      interval: "daily"

  # - package-ecosystem: "pip"
  #   directory: "/Qualidade-de-Software/backend/dama"
  #   target-branch: "main"
  #   schedule:
  #     interval: "weekly"
  #   open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
